descriptor_extension: yml
package:
  description: SONATA HSP LOWER SP VTC
  maintainer: Thomas Soenen, imec, thomas.soenen@ugent.be
  name: "son-hsp-lowersp-vtc"
  vendor: "eu.sonata-nfv"
  version: "0.1"
version: '0.5'
